return {
  "amadeus/nvim-highlight-colors",
  enabled = false,
  opts = {
    render = "virtual",
    virtual_symbol_position = "eol",
    virtual_symbol = "●",
    virtual_symbol_suffix = "",
    enable_hex = true,
    enable_short_hex = true,
    enable_rgb = true,
    enable_hsl = true,
    enable_ansi = true,
    enable_hsl_without_function = true,
    enable_var_usage = true,
    enable_named_colors = true,
    enable_tailwind = false,
    exclude_filetypes = { "floggraph", "git", "codecompanion" },
  },
}
